# Generated by Django 3.1.7 on 2021-03-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210304_1805'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='geo_data',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AddField(
            model_name='profile',
            name='geolocation_appointment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.DeleteModel(
            name='GeoData',
        ),
    ]
