# Generated by Django 3.1.7 on 2021-03-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20210304_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='geolocation_appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
